name: prettier
title: Prettier • Opinionated Code Formatter
version: "3.4.2"
base: core24
summary: An opinionated code formatter that works with many languages.
description: TODO

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  riscv64:
  s390x:

parts:
  prettier:
    plugin: npm
    npm-include-node: true
    npm-node-version: "22"
    source: https://github.com/prettier/prettier.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION


apps:
  prettier:
    command: bin/prettier
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    plugs:
      - home
    # completer: uv-completion.bash
